// Fala entre Lucina e Chrom
import { Translations } from "./characterDialogues";

export const ChromLucinaDialogues: Translations = {
    // Falas em inglês
    en: {
        prompt1: "Might I ask a lesson, Chrom? I would love to learn the sword from you.",
        prompt2: "You're a master in your own right already. What could I possibly teach you?",
        prompt3: "You're likely better served training alone where you can hone your own style.",
        prompt4: "But I was hoping that you might... That we could...",
        prompt5: "Hmm?",
        prompt6: "...I'm sorry. If it's a bother, I won't insist.",
        prompt7: "I never said it was a bother. I just meant that with your level of skill, you'd be...",
        prompt8: "......",
        prompt9: "...Heh. Fine. Go fetch a pair of practice blades",
        prompt10: "Wonderful! I just so happen to have two right here...",
        prompt11: "Well, someone's certainly prepared. Very well, let's begin.",
        prompt12: "Yes, sir!",
        prompt13: "Hnngh!",
        prompt14: "Yaaah!",
        prompt15: "Ngh...",
        prompt16: "...Urgh!",
        prompt17: "...Impressive as ever. I was certain I dodged that one, but you nicked my shoulder.",
        prompt18: "Still, you had me soundly beat.",
        prompt19: "Had you not held back on that blow to my chest, I'd have a few shattered ribs.",
        prompt20: "I was right to think you still have much to teach me.",
        prompt21: "We'll have to make these lessons a habit.",
        prompt22: "Wait, you didn't just...",
        prompt23: "Did you throw that match just so we'd continue doing this?",
        prompt24: "Why, Chrom... I would never!",
        prompt25: "...Devious. I see I'll have to keep a closer eye on you, heh.",
    },
    // Falas em português brasileiro
    pt: {
        prompt1: "Posso pedir uma lição, Chrom? Adoraria aprender a espada contigo.",
        prompt2: "Você já é uma mestre por direito próprio. O que eu poderia possivelmente te ensinar?",
        prompt3: "Você provavelmente se beneficiaria mais treinando sozinha, onde pode aprimorar seu próprio estilo.",
        prompt4: "Mas eu estava esperando que você pudesse... Que nós pudéssemos...",
        prompt5: "Hmm?",
        prompt6: "...Desculpe. Se estiver incomodando, não vou insistir.",
        prompt7: "Nunca disse que estava incomodando. Só quis dizer que com seu nível de habilidade, você seria...",
        prompt8: "......",
        prompt9: "...Heh. Tudo bem. Vá buscar um par de espadas de treino.",
        prompt10: "Maravilhoso! Eu tenho exatamente duas aqui...",
        prompt11: "Bem, alguém está definitivamente preparada. Muito bem, vamos começar.",
        prompt12: "Sim, senhor!",
        prompt13: "Hnngh!",
        prompt14: "Yaaah!",
        prompt15: "Ngh...",
        prompt16: "...Urgh!",
        prompt17: "...Impressionante como sempre. Eu estava certo de que desviei daquele, mas você acertou meu ombro.",
        prompt18: "Ainda assim, você me derrotou completamente.",
        prompt19: "Se não tivesse segurado naquele golpe no meu peito, eu teria algumas costelas quebradas.",
        prompt20: "Eu estava certa em pensar que você ainda tem muito a me ensinar.",
        prompt21: "Teremos que tornar essas lições um hábito.",
        prompt22: "Espere, você não fez isso...",
        prompt23: "Você jogou essa partida apenas para continuarmos fazendo isso?",
        prompt24: "Por que, Chrom... Eu jamais faria isso!",
        prompt25: "...Astuta. Vejo que vou ter que ficar de olho em você, heh.",
    },
    // Falas em alemão
    
    de: {
        prompt1: "Darf ich um eine Lektion bitten, Chrom? Ich würde gerne von dir das Schwertspiel lernen.",
        prompt2: "Du bist bereits eine Meisterin aus eigenem Recht. Was könnte ich dir schon beibringen?",
        prompt3: "Du würdest wahrscheinlich mehr davon profitieren, alleine zu trainieren, wo du deinen eigenen Stil verfeinern kannst.",
        prompt4: "Aber ich hatte gehofft, dass du... dass wir...",
        prompt5: "Hmm?",
        prompt6: "...Entschuldigung. Wenn es dich stört, werde ich nicht darauf bestehen.",
        prompt7: "Habe nie gesagt, dass es mich stört. Ich wollte nur sagen, dass mit deinem Können wärst du...",
        prompt8: "......",
        prompt9: "...Heh. In Ordnung. Hol ein paar Übungsschwerter.",
        prompt10: "Wunderbar! Ich habe genau zwei hier...",
        prompt11: "Nun, jemand ist definitiv vorbereitet. Gut, lass uns anfangen.",
        prompt12: "Ja, Herr!",
        prompt13: "Hnngh!",
        prompt14: "Yaaah!",
        prompt15: "Ngh...",
        prompt16: "...Urgh!",
        prompt17: "...Beeindruckend wie immer. Ich war sicher, dass ich diesem ausgewichen bin, aber du hast meine Schulter getroffen.",
        prompt18: "Dennoch hast du mich völlig besiegt.",
        prompt19: "Wenn du diesen Schlag nicht auf meiner Brust abgefangen hättest, hätte ich ein paar gebrochene Rippen.",
        prompt20: "Ich hatte recht zu denken, dass du mir noch viel beibringen kannst.",
        prompt21: "Wir sollten diese Lektionen zur Gewohnheit machen.",
        prompt22: "Warte, das hast du nicht...",
        prompt23: "Du hast dieses Spiel nur gespielt, um weiterzumachen, oder?",
        prompt24: "Warum, Chrom... Ich würde so etwas niemals tun!",
        prompt25: "...Schlau. Ich sehe, ich muss ein Auge auf dich haben, heh.",
    },
}