// Fala entre Chrom e Gaius
import { Translations } from "./characterDialogues"

export const ChromGaiusDialogues: Translations = {
    en: {
        prompt1: "Gaius, do you have a moment?",
        prompt2: "What's up, Blue?",
        prompt3: "...Blue?",
        prompt4: "Er, right. Well, you must have traveled a lot in your old line of work, yes?",
        prompt5: "Sure did! Us thieves tend to outstay our welcome in a hurry.",
        prompt6: "The reason I ask is that I've had little chance to see the world properly.",
        prompt7: "I've journeyed on diplomatic business, but that's pretty much it.",
        prompt8: "And frankly, one majestic court looks very much like another.",
        prompt9: "I've often wondered what it would be like to roam the world free of royal burdens.",
        prompt10: "Ha! You royals up in your pointy towers really don't have a clue!",
        prompt11: "You think us commoners are free to just spend our days sauntering along!",
        prompt12: "Think we pick daisies and gaze at tourist attractions and eat bonbons all day!",
        prompt13: "Look, that's not what I was implying at all. ...And I think you know it.",
        prompt14: "So what's the problem? Tired of silk pants and the undying adoration of the masses?",
        prompt15: "I try to appreciate my situation, but being a royal can be incredibly...stifling.",
        prompt16: "It's a comfortable prison, true, but a prison nonetheless.",
        prompt17: "Sounds like a serious case of not being able to count your blessings.",
        prompt18: "It's true—I'm never hungry, I've a hot bath and a warm bed, people leap to my aid...",
        prompt19: "Perhaps you're right. What right have I to complain of such a life?",
        prompt20: "Bingo.",
    },
    pt: {
        prompt1: "Gaius, você tem um momento?",
        prompt2: "O que foi, Blue?",
        prompt3: "...Blue?",
        prompt4: "Er, certo. Bem, você deve ter viajado bastante em seu antigo trabalho, não é?",
        prompt5: "Certamente! Nós ladrões tendemos a não ser bem-vindos por muito tempo.",
        prompt6: "A razão pela qual pergunto é que tive pouca chance de ver o mundo adequadamente.",
        prompt7: "Viajei a negócios diplomáticos, mas é basicamente isso.",
        prompt8: "E, francamente, uma corte majestosa se parece muito com outra.",
        prompt9: "Muitas vezes, me perguntei como seria vagar pelo mundo sem as cargas reais.",
        prompt10: "Ha! Vocês, reais, lá em suas torres pontiagudas, realmente não têm ideia!",
        prompt11: "Acham que nós, plebeus, somos livres para passar nossos dias vagando por aí?",
        prompt12: "Acham que escolhemos margaridas, admiramos atrações turísticas e comemos bombons o dia todo?",
        prompt13: "Olha, não era isso que eu estava implicando. ...E acho que você sabe disso.",
        prompt14: "Então, qual é o problema? Cansado de calças de seda e da adoração interminável das massas?",
        prompt15: "Tento apreciar minha situação, mas ser um nobre pode ser incrivelmente... sufocante.",
        prompt16: "É uma prisão confortável, é verdade, mas é uma prisão mesmo assim.",
        prompt17: "Parece um sério caso de não saber contar suas bênçãos.",
        prompt18: "É verdade, nunca passo fome, tenho uma banheira quente e uma cama aconchegante, as pessoas correm para me ajudar...",
        prompt19: "Talvez você tenha razão. Que direito tenho de reclamar de uma vida assim?",
        prompt20: "Bingo.",
    },
    de: {
        prompt1: "Gaius, hast du einen Moment?",
        prompt2: "Was gibt's, Blue?",
        prompt3: "...Blue?",
        prompt4: "Äh, richtig. Nun, du musst in deinem alten Beruf viel gereist sein, oder?",
        prompt5: "Das stimmt! Wir Diebe neigen dazu, unseren Aufenthalt schnell zu überziehen.",
        prompt6: "Der Grund, warum ich frage, ist, dass ich wenig Gelegenheit hatte, die Welt richtig zu sehen.",
        prompt7: "Ich bin zu diplomatischen Geschäften gereist, aber das war es auch schon.",
        prompt8: "Und ehrlich gesagt sieht eine majestätische Höfe ziemlich gleich aus.",
        prompt9: "Ich habe mich oft gefragt, wie es wäre, ohne königliche Lasten frei durch die Welt zu ziehen.",
        prompt10: "Ha! Ihr Adligen da oben in euren spitz zulaufenden Türmen habt wirklich keine Ahnung!",
        prompt11: "Ihr denkt, wir Normalos sind frei, den ganzen Tag gemütlich herumzulaufen!",
        prompt12: "Denkt ihr, wir pflücken Gänseblümchen, bestaunen Touristenattraktionen und essen den ganzen Tag Bonbons!",
        prompt13: "Schau, das war überhaupt nicht, was ich andeuten wollte. ...Und ich denke, das weißt du.",
        prompt14: "Also, wo liegt das Problem? Müde von Seidenhosen und der unsterblichen Verehrung der Massen?",
        prompt15: "Ich versuche, meine Situation zu schätzen, aber königlich zu sein, kann unglaublich... erdrückend sein.",
        prompt16: "Es ist zwar ein bequemes Gefängnis, aber ein Gefängnis trotzdem.",
        prompt17: "Klingt nach einem ernsten Fall von undankbar sein.",
        prompt18: "Es ist wahr - ich habe nie Hunger, ich habe ein heißes Bad und ein warmes Bett, die Leute springen, um mir zu helfen...",
        prompt19: "Vielleicht hast du recht. Welches Recht habe ich, mich über so ein Leben zu beschweren?",
        prompt20: "Bingo.",
    }
}