// Fala entre Tharja e Gaius
import { Translations } from "./characterDialogues"

export const GaiusTharjaDialogues: Translations = {
    en: {
        prompt1: "You.",
        prompt2: "Me?",
        prompt3: "Yes, you. You're a thief, right? Skilled at pilfering and all that?",
        prompt4: "I've got a little job for you.",
        prompt5: "I'm listening...",
        prompt6: "I want you to bring me a strand of Lucina's hair.",
        prompt7: "That's...unbelievably creepy. What do you need her hair for?",
        prompt8: "Hee hee...",
        prompt9: "Um, yeah. I don't usually take sinister chuckles as an answer.",
        prompt10: "Sorry, kid. Go find someone else to help with your weird hobbies.",
        prompt11: "This is not a negotiable request.",
        prompt12: "Oh? And what are you going to do about it, Sunshine? Curse me?",
        prompt13: "Yes.",
        prompt14: "Heh. Ain't a hexer alive that's managed to put a curse on Gaius the Nimble!",
        prompt15: "Go on, Sunshine. Do your worst.",
        prompt16: "You are making a terrible mistake...",
        prompt17: "Ooh! So scaaary! Do you see me shaking here?",
    },
    pt: {
        prompt1: "Você.",
        prompt2: "Eu?",
        prompt3: "Sim, você. Você é um ladrão, certo? Habilidoso em furtos e tudo mais?",
        prompt4: "Eu tenho um pequeno trabalho para você.",
        prompt5: "Estou ouvindo...",
        prompt6: "Eu quero que você traga uma mecha do cabelo da Lucina.",
        prompt7: "Isso é... incrivelmente estranho. Para que você precisa do cabelo dela?",
        prompt8: "Hee hee...",
        prompt9: "Um, sim. Eu geralmente não aceito risadas sinistras como resposta.",
        prompt10: "Desculpe, garota. Vá procurar outra pessoa para ajudar com seus hobbies bizarros.",
        prompt11: "Isso não é um pedido negociável.",
        prompt12: "Ah, é? E o que você vai fazer a respeito, Sunshine? Me amaldiçoar?",
        prompt13: "Sim.",
        prompt14: "Heh. Não existe um encantador vivo que tenha conseguido amaldiçoar Gaius, o Ágil!",
        prompt15: "Vai em frente, Sunshine. Faça o seu pior.",
        prompt16: "Você está cometendo um terrível engano...",
        prompt17: "Ooh! Tão assustador! Você me vê tremendo aqui?",
    },
    de: {
        prompt1: "Du.",
        prompt2: "Ich?",
        prompt3: "Ja, du. Du bist ein Dieb, oder? Geschickt im Stehlen und so?",
        prompt4: "Ich habe einen kleinen Job für dich.",
        prompt5: "Ich höre...",
        prompt6: "Ich möchte, dass du mir eine Strähne von Lucinas Haar bringst.",
        prompt7: "Das ist... unglaublich gruselig. Wofür brauchst du ihr Haar?",
        prompt8: "Hee hee...",
        prompt9: "Ähm, ja. Normalerweise betrachte ich böses Lachen nicht als Antwort.",
        prompt10: "Entschuldigung, Mädchen. Such dir jemand anderen, um bei deinen seltsamen Hobbys zu helfen.",
        prompt11: "Das ist keine verhandelbare Bitte.",
        prompt12: "Oh? Und was wirst du dagegen tun, Sunshine? Mich verfluchen?",
        prompt13: "Ja.",
        prompt14: "Heh. Es gibt keine Hexe, die es geschafft hat, Gaius den Wendigen zu verfluchen!",
        prompt15: "Komm schon, Sunshine. Tu dein Schlimmstes.",
        prompt16: "Du machst einen schrecklichen Fehler...",
        prompt17: "Ooh! So gruselig! Siehst du, wie ich hier zittere?",
    }
}